site_name: Free Pascal & Lazarus Cookbook
site_url: https://learn-pascal-lang.org
nav:
  - Home: 
    - Overview: index.md
    - About: about.md
    - License: LICENSE.md
  - Core Tasks:
    - Overview: docs/basics/overview.md
    - Install FPC and Lazarus: docs/basics/install.md
    - Lazarus IDE: docs/basics/lazarus-ide.md
    - Code Structure: docs/basics/code-structure.md
    - Run a "Hello World!": docs/basics/hello-world.md
    - Command Line Parameters: docs/basics/cmd-line-params.md
    - Functions & Procedures: docs/basics/funcs-procs.md
    - Immutability: docs/basics/immutability.md
    - Loops: docs/basics/loops.md
    - Arrays: docs/basics/arrays.md
    - Lists: docs/basics/lists.md 
    - Strings: docs/basics/strings.md
    - Numbers: docs/basics/numbers.md
    - Dates & Times: docs/basics/dates.md
    - Regular Expressions: docs/basics/regex.md
    - Directories, Paths and Files: docs/basics/dir-path-filename.md
    - Exceptions: docs/basics/exception-try-blocks.md
    - File Handling I: docs/basics/file-handling.md
    - File Handling II: docs/basics/file-handling-ii.md

  - Advanced Topics:
    - Overview: docs/advanced/overview.md
    - Conditional Compilation: docs/advanced/conditional-compilation.md
    - Debugging: docs/advanced/debugging.md
    - Multi-threading Basics: docs/advanced/multi-threading-basics.md
    - Multi-threading Creation: docs/advanced/multi-threading-creation.md
    - Multi-threading Snippets: docs/advanced/multi-threading-snippets.md
  - External Systems:
    - Overview: docs/external-systems/overview.md
    - Parsing JSON: docs/external-systems/parsing-json.md
    - Web Server: docs/external-systems/webserver.md
  - Community: community.md
  - Resources:
    - Documents & Sites: docs/resources/docs-sites.md
    - FPC & Lazarus Packages: docs/resources/fpc-laz-packages.md
    - Videos: docs/resources/videos.md

theme:
  name: material
  logo: assets/logo-new-rounded-min.png
  favicon: assets/logo-new-rounded-min.png
  font: 
    text: Roboto
    code: Roboto Mono
  palette:
        # Palette toggle for light mode
    - scheme: default
      primary: blue
      accent: orange
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: blue
      accent: orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.path
    - toc.follow
    - search.suggest
    - search.highlight
    - content.code.copy

plugins:
  - search
#  - enumerate-headings:
#      toc_depth: 6
#      increment_across_pages: true
#      exclude:
#          - index.md
#          - about.md
#          - LICENSE.md
  - open-in-new-tab
  - glightbox:
      touchNavigation: true
      loop: false
      effect: zoom
      slide_effect: slide
      width: auto
      height: auto
      zoomable: true
      draggable: true


markdown_extensions:
  - attr_list
  - md_in_html
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      use_pygments: true
      pygments_lang_class: true
      anchor_linenums: true
      line_spans: __span
  - admonition
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.smartsymbols
  - pymdownx.betterem
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.keys
  - pymdownx.critic
  - sane_lists
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js