site_name: Free Pascal Cookbook
site_url: https://learn-pascal-lang.org
nav:
  - Home: 
    - Overview: index.md
    - About: about.md
    - License: LICENSE.md
  - The Basics:
    - Install: docs/basics/install.md
    - Run a "Hello World!": docs/basics/hello-world.md
    - Structuring Your Codes: docs/basics/pascal-code-structure.md
    - Building and Processing Lists: docs/basics/lists.md
    - Immutability: docs/basics/immutability.md
    - Functions & Procedures: docs/basics/funcs-procs.md
    - Data Structures: docs/basics/data-structure.md
    - Strings: docs/basics/strings.md
    - Regular Expressions: docs/basics/regex.md
    - Numbers: docs/basics/numbers.md
    - Loops, iteration, mapping: docs/basics/loops-iter.md
    - Multidimensional Arrays: docs/basics/multi-dim-arrays.md
    - Dates and Times: docs/basics/dates.md
    - Pattern Matching: docs/basics/pattern.md
    - Input/Output: docs/basics/io.md
    - Files and Directories: docs/basics/files-dir.md
  - Advanced Topics:
    - Creating Packages: docs/advanced/create-packages.md
    - Creating Units: docs/advanced/create-units.md
    - Error and condition handling: docs/advanced/error-condition.md
    - Debugging: docs/advanced/debugging.mg
    - Macros and Backquote: docs/advanced/macros.md
    - Type System: docs/advanced/types.md
    - Concurrency and Parallelism: docs/advanced/concurrent-parallel.md
    - Performance Tuning: docs/advanced/performance.md
    - Testing and Continuous Integration: docs/advanced/testing.md
    - Scripting. Building executables: docs/advanced/compile.md
    - Miscellaneous: docs/advanced/misc.md
  - External Systems:
    - Overview: docs/external-systems/overview.md
  - Community: community.md
  - Other Resources:
    # - Cheatsheet: docs/resources/cheatsheet.md
    - Documents & Sites: docs/resources/docs-sites.md
    - FPC & Lazarus Packages: docs/resources/fpc-laz-packages.md
    - Videos: docs/resources/videos.md

theme:
  name: material
  logo: assets/logo.png
  favicon: assets/favicon.png
  font: 
    text: Roboto
    code: Fira Code
  palette:
        # Palette toggle for light mode
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.path
    - toc.follow
    - search.suggest
    - search.highlight

plugins:
  - search
  - open-in-new-tab

markdown_extensions:
  - attr_list
  - md_in_html
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      use_pygments: true
      pygments_lang_class: true
      anchor_linenums: true
      line_spans: __span
  - admonition
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.smartsymbols
  - pymdownx.betterem
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.keys
  - pymdownx.critic
  - sane_lists

  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js